# Generated by Django 5.0.1 on 2024-10-21 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_customuser_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='Bio',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='interested',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='locations',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='viewersprofilemodel',
            name='preferred_content_type',
            field=models.CharField(choices=[('articlse', 'Articlse'), ('videos', 'Videos'), ('both', 'Both')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='bologerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bio', models.TextField(max_length=100, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('locations', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creatorsProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='creatorProfileModel',
        ),
    ]
