# Generated by Django 5.0.1 on 2024-10-21 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_viewersprofilemodel_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bologerprofilemodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bologerProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
